[project]
name = "table-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=36.2.2",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.396",
    "ruff>=0.9.9",
]
